python TrainCNO_rel_l2.py shear_layer
python TrainCNO_rel_l2.py poisson
python TrainCNO_rel_l2.py wave_0_5
python TrainCNO_rel_l2.py allen
python TrainCNO_rel_l2.py cont_tran
python TrainCNO_rel_l2.py disc_tran
python TrainCNO_rel_l2.py airfoil
python TrainCNO_rel_l2.py darcy
python TrainCNO_rel_l2.py ns
